global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']  # Scrape Collector's own metrics
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['otel-collector:9090']  # Scrape application metrics