global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-latency200-1ppdm-50'
    static_configs:
      - targets: ['10.198.28.188:8888']  # Scrape Collector's own metrics
  - job_name: 'data-collector-latency200-1ppdm-50'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.198.28.188:8456']  # Scrape application metrics
  - job_name: 'data-exporter-latency200-1ppdm-50'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.198.28.188:18456']  # Scrape application metrics